### ISSUE TITLE
[Bug]: Using in Filament tables - nothing showing in the table columns - is this as expected?

### ISSUE THREAD

**Issue by jj63systems** [solutionforest/Filament-SimpleLightBox#16]
### What happened?

I installed per instructions (using composer) and added to my AdminPanelProvider.php file

`use SolutionForest\FilamentSimpleLightBox\SimpleLightBoxPlugin;
`
and

            ->plugin(SimpleLightBoxPlugin::make())

My page looks like this:

![image](https://github.com/user-attachments/assets/119ed5e1-a052-4920-8ca0-5cde922d9a1b)

You'll see the column headings. The code to generate these column headings is

```
                Tables\Columns\ImageColumn::make('image')
                    ->simpleLightbox('https://picsum.photos/id/237/200/300'),
                Tables\Columns\TextColumn::make('pdf_url')
                    ->simpleLightbox("https://www.princexml.com/samples/invoice/invoicesample.pdf"),

```

There is no icon or placeholder displayed. If I click generally in the "cell" where I would expect to see a placeholder, for images nothing happens. Under the PDF column it does then open the PDF document referenced.

### How to reproduce the bug

Nothing specific to add here.

### Package Version

0.0.7

### PHP Version

8.2

### Laravel Version

Laravel 10.44 / Filament v3

### Which operating systems does with happen with?

Linux

### Notes

Not sure if this is a bug or if there are additional steps required (which aren't as far as I can see documented). Thx

**Comment by lam0819** [comment]
we are reuse ImageColumn , and TextColumn

does your image and pdf_url exist?

**Comment by jj63systems** [comment]
Yes the URLs do resolve to documents (randomly selected) on the internet.

Is there code I can add that will help to debug?

**Comment by lam0819** [comment]
https://github.com/solutionforest/Filament-SimpleLightBox/releases/tag/0.0.8
see this help
