### ISSUE TITLE
Multiple images, show next image - not a bug i think

### ISSUE THREAD

**Issue by aliaswpeu** [solutionforest/Filament-SimpleLightBox#3]
### What happened?

I'm using Spatie medialibrary plugin and i want to show all images (using next and previous arrows to swich images) in lightbox - but using Your plugin I can only show one. Can You tell me is it possible using Your plugin to achieve this ? If not, are You planning on addig this functionality ?

### How to reproduce the bug

only one image from collection

### Package Version

0.04

### PHP Version

8.2

### Laravel Version

10

**Comment by lam0819** [comment]
how do you show multiple images now ?any code can show me ?

**Comment by aliaswpeu** [comment]
I'm using spatie medialibrary, so it loads as stacked images

`

SpatieMediaLibraryImageColumn::make('images')
                                ->label('Pics')
                                ->collection('veh-images')
                                ->stacked()->extraImgAttributes(['loading' => 'lazy'])
                                ->ring(2)
                                ->conversion('web')
                                ->overlap(5)
                                ->limit(5)
                                ->size(150),

`

**Comment by lam0819** [comment]
@aliaswpeu support Multiple Image now.

**Comment by aliaswpeu** [comment]
> @aliaswpeu support Multiple Image now.

Thank You! I will test this ASAP!

**Comment by aliaswpeu** [comment]
Hi, This works great! However - i would like to show only one image in table row from collection but when user clicks the lightbox will be able to show next image too (all from collection).

SpatieMediaLibraryImageColumn::make('images') 
->label('Pics')
 ->collection('veh-images')
->stacked()
->extraImgAttributes(['loading' => 'lazy'])
->conversion('web')
->limit(1) ->size(150)->simpleLightbox()

Is that possible ?

Thank You!
