### ISSUE TITLE
[Bug]: Cannot generate URL using closure function

### ISSUE THREAD

**Issue by arbet** [solutionforest/Filament-SimpleLightBox#7]
### What happened?

I expected to be able to pass dynamically a URL and it would take it dynamically

### How to reproduce the bug

Check this code 
```

ImageColumn::make('thumbnail_path')
                    ->size(150)
                    ->label('Media')
                    ->simpleLightbox(fn (PublicInstagramPost $record) => asset('storage/'.$record->media_path)),
```
It gives this error 

`Object of class Closure could not be converted to string`

I should be able to dynamically load the lightbox

### Package Version

0.0.5

### PHP Version

8.2.14

### Laravel Version

10.40.0

### Which operating systems does with happen with?

Linux

**Comment by abbasmashaddy72** [comment]
I am also having same issue

**Comment by NicholasMartens** [comment]
Same here

**Comment by maytham553** [comment]
same issue

**Comment by baraakhateeb** [comment]
same here

**Comment by lam0819** [comment]
see this help

https://github.com/solutionforest/Filament-SimpleLightBox/releases/tag/0.0.8

**Comment by Jason6809** [comment]
Issue still exist.
