### ISSUE TITLE
[Bug]: Bug when using SPA mode

### ISSUE THREAD

**Issue by wisnuwirayuda15** [solutionforest/Filament-SimpleLightBox#9]
### What happened?

When I use SPA mode, the lightbox will appear temporarily and then switch pages, resulting in all pages being unscrollable.

### How to reproduce the bug

This bug only happens when I use SPA mode.

### Package Version

0.0.5

### PHP Version

8.3.2

### Laravel Version

10.48.3

### Which operating systems does with happen with?

Windows

**Comment by lam0819** [comment]
will look into , similar case , not load the js when using SPA mode
https://github.com/filamentphp/filament/pull/11647
